"""create Restaurant and Speisen tables

Revision ID: ce14e08bf7d3
Revises: 
Create Date: 2025-10-07 11:21:53.272025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce14e08bf7d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Restaurant',
    sa.Column('r_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('r_ID')
    )
    op.create_table('Speisen',
    sa.Column('s_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('Preis', sa.Float(), nullable=False),
    sa.Column('Datum', sa.Date(), nullable=False),
    sa.Column('r_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['r_ID'], ['Restaurant.r_ID'], ),
    sa.PrimaryKeyConstraint('s_ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Speisen')
    op.drop_table('Restaurant')
    # ### end Alembic commands ###
